version: '3.0'

volumes:
  peer0.org1.example.com: {}
  peer0.org2.example.com: {}
  peer0.org3.example.com: {}
  peer1.org1.example.com: {}
  peer1.org2.example.com: {}
  peer1.org3.example.com: {}

networks:
  cloudExNet:
    external:
      name: cloudExNet


services:
  caorg1examplecom:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${org1ca}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${org1ca}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      -  ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      cloudExNet:
        aliases:
           - ca.org1.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  peer0org1examplecom:
    command: peer node start
    container_name: peer0.org1.example.com
    environment:
      FABRIC_LOGGING_SPEC: INFO
      
      CORE_PEER_ID: peer0.org1.example.com
      CORE_PEER_ADDRESS: peer0.org1.example.com:7051
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      
      CORE_PEER_GOSSIP_BOOTSTRAP: peer1.org1.example.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.org1.example.com:7051
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_LOCALMSPID: Org1MSP
      CORE_PEER_PROFILE_ENABLED: "true"

      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: cloudExNet
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
    image: hyperledger/fabric-peer:latest
    networks:
      cloudExNet:
        aliases:
           - peer0.org1.example.com
    ports:
    - 7051:7051/tcp
    - 7053:7053/tcp
    volumes:
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp:rw
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls:rw
    - /var/run:/host/var/run:rw
    - peer0.org1.example.com:/var/hyperledger/production:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure



  peer1org1examplecom:
    command: peer node start
    container_name: peer1.org1.example.com
    environment:
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_ADDRESS: peer1.org1.example.com:7051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.org1.example.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer1.org1.example.com:7051
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_ID: peer1.org1.example.com
      CORE_PEER_LOCALMSPID: Org1MSP
      CORE_PEER_PROFILE_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: cloudExNet
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
    image: hyperledger/fabric-peer:latest
    networks:
      cloudExNet:
        aliases:
           - peer1.org1.example.com
    ports:
    - 8051:7051/tcp
    - 8053:7053/tcp
    volumes:
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp:rw
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls:rw
    - /var/run:/host/var/run:rw
    - peer1.org1.example.com:/var/hyperledger/production:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure




# =============================================================================================================================================



  caorg2examplecom:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${org2ca}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${org2ca}
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      cloudExNet:
        aliases:
           - ca.org2.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  peer0org2examplecom:
    command: peer node start
    container_name: peer0.org2.example.com
    environment:
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_ADDRESS: peer0.org2.example.com:7051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer1.org2.example.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.org2.example.com:7051
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_ID: peer0.org2.example.com
      CORE_PEER_LOCALMSPID: Org2MSP
      CORE_PEER_PROFILE_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: cloudExNet
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
    image: hyperledger/fabric-peer:latest
    networks:
      cloudExNet:
        aliases:
           - peer0.org2.example.com
    ports:
    - 9051:7051/tcp
    - 9053:7053/tcp
    volumes:
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp:rw
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls:rw
    - /var/run:/host/var/run:rw
    - peer0.org2.example.com:/var/hyperledger/production:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure



  peer1org2examplecom:
    command: peer node start
    container_name: peer1.org2.example.com
    environment:
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_ADDRESS: peer1.org2.example.com:7051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.org2.example.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer1.org2.example.com:7051
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_ID: peer1.org2.example.com
      CORE_PEER_LOCALMSPID: Org2MSP
      CORE_PEER_PROFILE_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: cloudExNet
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
    image: hyperledger/fabric-peer:latest
    networks:
      cloudExNet:
        aliases:
           - peer1.org2.example.com
    ports:
    - 10051:7051/tcp
    - 10053:7053/tcp
    volumes:
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp:rw
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls:rw
    - /var/run:/host/var/run:rw
    - peer1.org2.example.com:/var/hyperledger/production:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure




# =============================================================================================================================================




  caorg3examplecom:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${org3ca}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${org3ca}
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg3
    networks:
      cloudExNet:
        aliases:
           - ca.org3.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  peer0org3examplecom:
    command: peer node start
    container_name: peer0.org3.example.com
    environment:
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_ADDRESS: peer0.org3.example.com:7051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer1.org3.example.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.org3.example.com:7051
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_ID: peer0.org3.example.com
      CORE_PEER_LOCALMSPID: Org3MSP
      CORE_PEER_PROFILE_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: cloudExNet
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
    image: hyperledger/fabric-peer:latest
    networks:
      cloudExNet:
        aliases:
           - peer0.org3.example.com
    ports:
    - 11051:7051/tcp
    - 11053:7053/tcp
    volumes:
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp:rw
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls:rw
    - /var/run:/host/var/run:rw
    - peer0.org3.example.com:/var/hyperledger/production:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  peer1org3examplecom:
    command: peer node start
    container_name: peer1.org3.example.com
    environment:
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_ADDRESS: peer1.org3.example.com:7051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.org3.example.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer1.org3.example.com:7051
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_ID: peer1.org3.example.com
      CORE_PEER_LOCALMSPID: Org3MSP
      CORE_PEER_PROFILE_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: cloudExNet
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
    image: hyperledger/fabric-peer:latest
    networks:
      cloudExNet:
        aliases:
           - peer1.org3.example.com
    ports:
    - 12051:7051/tcp
    - 12053:7053/tcp
    volumes:
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/fabric/msp:rw
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/fabric/tls:rw
    - /var/run:/host/var/run:rw
    - peer1.org3.example.com:/var/hyperledger/production:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  cli:
    command: /bin/bash
    container_name: cli
    # depends_on:
    # - orderer.example.com
    # - peer0.org1.example.com
    # - peer0.org2.example.com
    # - peer0.org3.example.com
    # - peer1.org1.example.com
    # - peer1.org2.example.com
    # - peer1.org3.example.com
    environment:
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_ADDRESS: peer0.org1.example.com:7051
      CORE_PEER_ID: cli
      CORE_PEER_LOCALMSPID: Org1MSP
      CORE_PEER_MSPCONFIGPATH: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      CORE_PEER_TLS_CERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_KEY_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      GOPATH: /opt/gopath
    image: hyperledger/fabric-tools:latest
    networks:
      cloudExNet:
    stdin_open: true
    tty: true
    volumes:
    - /var/run:/host/var/run:rw
    - ./myChaincode:/opt/gopath/src/github.com/chaincode:rw
    - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto:rw
    - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts:rw
    - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

